name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        addons: ["control-plane-addon","execution-plane-addon"]
    steps:
      - uses: actions/checkout@v2
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci --ignore-scripts
        working-directory: ./${{ matrix.addons }}

      - run: npm run lint
        working-directory: ./${{ matrix.addons }}
        name: Lint

      - run: npm run build --if-present
        working-directory: ./${{ matrix.addons }}
        name: Build

      - run: npm version ${{ github.event.release.tag_name }}
        working-directory: ./${{ matrix.addons }}
        name: Update Version Number

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}   
          package: ./${{ matrix.addons }}/package.json          

  trivy:
    needs: [build]
    name: Trivy Scan
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'HIGH,CRITICAL'
          scan-ref: ./${{ matrix.addons }}

  generate-dependencies:
    needs: [trivy]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Core Repo
        uses: actions/checkout@v2.4.0
        with:
          path: 'keptn-sandbox/keptn-ssp-addons'
      - name: Set up Node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14
      - name: Install npm libs
        run: |
          yarn global add license-report
      - name: Node dependencies and licenses - Execution Plane Add-On
        run: |
          echo "🔍 Analyzing dependencies in keptn-ep-add-on"
          ( cd keptn-sandbox/keptn-ssp-addons/execution-plane-addon || return ; license-report --only-prod --output=csv > ../../../dependencies-and-licenses-ep-addon.txt )
          echo
          echo "👍 done. written results to ./dependencies-and-licenses-ep-addon.txt"
          cat dependencies-and-licenses-ep-add-on.txt
      - name: Node dependencies and licenses - Control Plane Add-On
        run: |
          echo "🔍 Analyzing dependencies in keptn-cp-add-on"
          ( cd keptn-sandbox/keptn-ssp-addons/control-plane-addon || return ; license-report --only-prod --output=csv > ../../../dependencies-and-licenses-cp-addon.txt )
          echo
          echo "👍 done. written results to ./dependencies-and-licenses-cp-addon.txt"
          cat dependencies-and-licenses-cp-add-on.txt
      - name: Upload Release Asset - Control Plane Add-On SBOM
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./dependencies-and-licenses-cp-add-on.txt
          asset_name: dependencies-and-licenses-control-plane.txt
          asset_content_type: text/plain
      - name: Upload Release Asset - Execution Plane Add-On SBOM
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./dependencies-and-licenses-ep-add-on.txt
          asset_name: dependencies-and-licenses-execution-plane.txt
          asset_content_type: text/plain